export const FILTER_FOCUS_TURN_ON = 'FILTER_FOCUS_TURN_ON';
export const FILTER_FOCUS_TURN_OFF = 'FILTER_FOCUS_TURN_OFF';
export const FILTER_FOCUS_TOGGLE = 'FILTER_FOCUS_TURN_TOGGLE';

export const ITEM_ADD = 'ITEM_ADD';